before_install:
  - sudo apt-get install python3-dev luarocks npm
  - gem install rake-compiler
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python3
  - sudo luarocks install busted

install:
  - make
  - rm -f *.o
  - sudo luarocks make
  - rm -f *.o
  - python3 setup.py build
  - sudo python3 setup.py install
  - rm -rf build
  - sudo npm install
  - rake
  - rm -rf tmp

script:
  - rethinkdb --daemon
  - busted
