language: cpp

compiler:
  - clang
  - gcc
env:
  - |
    BUILD=build-py.sh
    TEST=test-py.sh
  - |
    BUILD=build-lua.sh
    TEST=test-lua.sh
  - |
    BUILD=build-node.sh
    TEST=test-node.sh
  - |
    BUILD=build-rb.sh
    TEST=test-rb.sh
  - |
    BUILD=build-c++.sh
    TEST=test-c++.sh

matrix:
  exclude:
    complier: gcc
    env: |
      BUILD=build-c++.sh
      TEST=test-c++.sh

before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb
  - rethinkdb --daemon

install:
  - bash $BUILD

script:
  - bash $TEST
