before_install:
  - sudo apt-get install python3-dev luarocks npm
  - gem install rake-compiler
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python3

install:
  - make
  - rm *.o
  - sudo luarocks make
  - rm *.o
  - sudo python3 setup.py install
  - rm -rf build
  - sudo npm install
  - rake
  - rm -rf tmp

