language: cpp

compiler:
  - clang
  - gcc
env:
  - |
    BUILD=build-py.sh
    TEST=
  - |
    BUILD=build-lua.sh
    TEST=busted
  - |
    BUILD=build-node.sh
    TEST=
  - |
    BUILD=build-rb.sh
    TEST=
  - |
    BUILD=build-c++.sh
    TEST="make test"

before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb
  - rethinkdb --daemon

install:
  - bash $BUILD

script:
  - $TEST
