sudo: false

language: cpp

compiler: clang

before_install:
  - curl -o test/catch.hpp https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
  - cd rethinkdb
  - ./configure --allow-fetch
  - make src/all -j2
  - ./build/release_clang/rethinkdb --daemon
  - cd ..

install:
  - make
  - make libReQLtest

script:
  - make test
