before_install:
  - sudo apt-get install python3-dev luarocks npm
  - gem install rake
  - curl https://bootstrap.pypa.io/get-pip.py | sudo python3

install:
  - make
  - sudo luarocks make
  - python3 setup.py install
  - npm install
  - rake
