language: cpp

env:
  - |
    BUILD=build-c++.sh
    TEST=test-c++.sh
  - |
    BUILD=build-py.sh
    TEST=test-py.sh
  - |
    BUILD=build-lua.sh
    TEST=test-lua.sh
  - |
    BUILD=build-node.sh
    TEST=test-node.sh
  - |
    BUILD=build-rb.sh
    TEST=test-rb.sh

before_install:
  - curl -o catch.h https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp
  - cd rethinkdb
  - ./configure --allow-fetch
  - make src/all
  - ./build/release_gcc/rethinkdb --daemon
  - cd ..

install:
  - bash $BUILD

script:
  - bash $TEST
